name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

env:
  CONTISL_CARS_PROJECT_TOKEN: ${{secrets.CONTISL_CARS_PROJECT_TOKEN}}
  CONTISL_DEMO_PROJECT_TOKEN: ${{secrets.CONTISL_DEMO_PROJECT_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deploy.outputs.page_url}}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build solution
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v4
